@echo off
call build.bat clean fdoom13h.exe
call build.bat clean fdoomati.exe
call build.bat clean fdoombwc.exe
call build.bat clean fdoomc16.exe
call build.bat clean fdoomcga.exe
call build.bat clean fdoomcvb.exe
call build.bat clean fdoome.exe
call build.bat clean fdoomhgc.exe
call build.bat clean fdoompcp.exe
call build.bat clean fdoomt1.exe
call build.bat clean fdoomt12.exe
call build.bat clean fdoomt25.exe
call build.bat clean fdoomt43.exe
call build.bat clean fdoomt50.exe
call build.bat clean fdoomvbd.exe
call build.bat clean fdoomvbr.exe
call build.bat clean fdoom.exe
call build.bat clean fdoommda.exe
call build.bat clean fdoomega.exe
call build.bat clean fdoomcah.exe
call build.bat clean fdoom512.exe
call build.bat clean fdoom400.exe
