#!/bin/sh

./rm fdoom*.exe
./build.sh clean
./build.sh fdoom.exe
./build.sh clean
./build.sh fdoomcga.exe
./build.sh clean
./build.sh fdoombwc.exe
./build.sh clean
./build.sh fdoomhgc.exe
./build.sh clean
./build.sh fdoomt1.exe
./build.sh clean
./build.sh fdoomt12.exe
./build.sh clean
./build.sh fdoomt25.exe
./build.sh clean
./build.sh fdoomt43.exe
./build.sh clean
./build.sh fdoomt86.exe
./build.sh clean
./build.sh fdoomt50.exe
./build.sh clean
./build.sh fdoomt52.exe
./build.sh clean
./build.sh fdoomvbr.exe
./build.sh clean
./build.sh fdoomvbd.exe
./build.sh clean
./build.sh fdoomv2.exe
./build.sh clean
./build.sh fdoompcp.exe
./build.sh clean
./build.sh fdoomcvb.exe
./build.sh clean
./build.sh fdoomc16.exe
./build.sh clean
./build.sh fdoomv16.exe
./build.sh clean
./build.sh fdoome16.exe
./build.sh clean
./build.sh fdoome.exe
./build.sh clean
./build.sh fdoom13h.exe
./build.sh clean
./build.sh fdoommda.exe
./build.sh clean
./build.sh fdoomati.exe
./build.sh clean
./build.sh fdoomew1.exe
./build.sh clean
./build.sh fdoome80.exe
./build.sh clean
./build.sh fdoomega.exe
./build.sh clean
./build.sh fdoomcah.exe
./stub.sh
