@echo off
call make.bat clean 13H
call make.bat clean ATI
call make.bat clean BWC
call make.bat clean C16
call make.bat clean C36
call make.bat clean CGA
call make.bat clean CVB
call make.bat clean E
call make.bat clean E16
call make.bat clean E36
call make.bat clean HGC
call make.bat clean PCP
call make.bat clean T1
call make.bat clean T12
call make.bat clean T25
call make.bat clean T43
call make.bat clean T50
call make.bat clean T52
call make.bat clean T86
call make.bat clean V2
call make.bat clean V16
call make.bat clean V36
call make.bat clean VBD
call make.bat clean VBR
call make.bat clean Y
call make.bat clean MDA
call make.bat clean EW1
call make.bat clean E80
call make.bat clean EGA
call make.bat clean CAH
call make.bat clean 512
