@echo off
call make.bat clean fdoom13h.exe
call make.bat clean fdoomati.exe
call make.bat clean fdoombwc.exe
call make.bat clean fdoomc16.exe
call make.bat clean fdoomcga.exe
call make.bat clean fdoomcvb.exe
call make.bat clean fdoome.exe
call make.bat clean fdoome16.exe
call make.bat clean fdoomhgc.exe
call make.bat clean fdoompcp.exe
call make.bat clean fdoomt1.exe
call make.bat clean fdoomt12.exe
call make.bat clean fdoomt25.exe
call make.bat clean fdoomt43.exe
call make.bat clean fdoomt50.exe
call make.bat clean fdoomt52.exe
call make.bat clean fdoomt86.exe
call make.bat clean fdoomv2.exe
call make.bat clean fdoomv16.exe
call make.bat clean fdoomvbd.exe
call make.bat clean fdoomvbr.exe
call make.bat clean fdoom.exe
call make.bat clean fdoommda.exe
call make.bat clean fdoomew1.exe
call make.bat clean fdoome80.exe
call make.bat clean fdoomega.exe
call make.bat clean fdoomcah.exe
call make.bat clean fdoom512.exe
