// #define DEBUG_MDA_ENABLED 1

// #define BOCHS_DEBUG_ENABLED 1

// #define DEBUG_FILE_ENABLED 1

// #define DEBUG_SERIAL_ENABLED 1
// #define DEBUG_SERIAL_BASE_IO 0x3F8
// #define DEBUG_SERIAL_BAUD 38400

// #define BOUNDS_CHECK_ENABLED 1
// #define ASSERT_ENABLED 1

// #define DEBUG_DIE_ON_BACKTRACE 1
// #define DEBUG_SHOW_BACKTRACE_ON_SCREEN 1
