#include <stdlib.h>
#include <dos.h>
#include <conio.h>
#include "ns_dpmi.h"
#include "ns_task.h"
#include "ns_cards.h"
#include "ns_user.h"
#include "ns_cms.h"
#include "ns_muldf.h"
#include "ns_inter.h"

#include "m_misc.h"
#include "options.h"
#include "doomstat.h"

static int CMS_Installed = 0;

static char *CMS_BufferStart;
static char *CMS_CurrentBuffer;
static int CMS_BufferNum = 0;
static int CMS_NumBuffers = 0;
static int CMS_TransferLength = 0;
static int CMS_CurrentLength = 0;

static char *CMS_SoundPtr;
volatile int CMS_SoundPlaying;

static task *CMS_Timer;

void (*CMS_CallBack)(void);

/*---------------------------------------------------------------------
   Function: CMS_ServiceInterrupt

   Handles interrupt generated by sound card at the end of a voice
   transfer.  Calls the user supplied callback function.
---------------------------------------------------------------------*/

static void CMS_SetRegister(unsigned short regAddr, unsigned char reg, unsigned char val)
{
    outp(regAddr + 1, reg); /* Select the register */
    outp(regAddr, val);     /* Set the value of the register */
}

static void CMS_Reset(void)
{
    int i;
    unsigned short port = 0x220;
    // Null all 20 registers (first SAA1099)
    for (i = 0; i < 20; i++){
        CMS_SetRegister(port, i, 0x00);
    }

    // Reset chip
    CMS_SetRegister(port, 0x1C, 0x02);

    // Enable chip
    CMS_SetRegister(port, 0x1C, 0x01);

    port += 2;

    // Null all 20 registers (second SAA1099)
    for (i = 0; i < 20; i++){
        CMS_SetRegister(port, i, 0x00);
    }

    // Reset chip
    CMS_SetRegister(port, 0x1C, 0x02);

    // Enable chip
    CMS_SetRegister(port, 0x1C, 0x01);
}

static void CMS_ServiceInterrupt(task *Task)
{
    unsigned short port = 0x220;

    unsigned char value0;
    unsigned char value1;

    unsigned char value = (unsigned char) *CMS_SoundPtr;

    outp(port + 1, 2);

    value = value / 16;

    value0 = value;
    value0 = value0 << 1;
    value0 = value0 & 0xF;
    value0 = (value0 << 4) | value0;

    CMS_SetRegister(port, 0x02, value0);

    value1 = value;

    if (value1 != 8)
    {
        value1 = 0xEE;
    }

    CMS_SetRegister(port, 0x05, value1);

    CMS_SoundPtr++;

    CMS_CurrentLength--;
    if (CMS_CurrentLength == 0)
    {
        // Keep track of current buffer
        CMS_CurrentBuffer += CMS_TransferLength;
        CMS_BufferNum++;
        if (CMS_BufferNum >= CMS_NumBuffers)
        {
            CMS_BufferNum = 0;
            CMS_CurrentBuffer = CMS_BufferStart;
        }

        CMS_CurrentLength = CMS_TransferLength;
        CMS_SoundPtr = CMS_CurrentBuffer;

        // Call the caller's callback function
        if (CMS_CallBack != NULL)
        {
            MV_ServiceVoc();
        }
    }
}

/*---------------------------------------------------------------------
   Function: CMS_StopPlayback

   Ends the transfer of digitized sound to the Sound Source.
---------------------------------------------------------------------*/

void CMS_StopPlayback(void)
{
    if (CMS_SoundPlaying)
    {
        TS_Terminate(CMS_Timer);
        CMS_SoundPlaying = 0;
        CMS_BufferStart = NULL;
    }
}

/*---------------------------------------------------------------------
   Function: CMS_BeginBufferedPlayback

   Begins multibuffered playback of digitized sound on the Sound Source.
---------------------------------------------------------------------*/

int CMS_BeginBufferedPlayback(
    char *BufferStart,
    int BufferSize,
    int NumDivisions,
    void (*CallBackFunc)(void))
{
    if (CMS_SoundPlaying)
    {
        CMS_StopPlayback();
    }

    CMS_CallBack = CallBackFunc;

    CMS_BufferStart = BufferStart;
    CMS_CurrentBuffer = BufferStart;
    CMS_SoundPtr = BufferStart;
    // VITI95: OPTIMIZE
    CMS_TransferLength = BufferSize / NumDivisions;
    CMS_CurrentLength = CMS_TransferLength;
    CMS_BufferNum = 0;
    CMS_NumBuffers = NumDivisions;

    CMS_SoundPlaying = 1;

    CMS_Timer = TS_ScheduleTask(CMS_ServiceInterrupt, CMS_SampleRate, 1, NULL);
    TS_Dispatch();

    return (CMS_Ok);
}

/*---------------------------------------------------------------------
   Function: CMS_Init

   Initializes the Sound Source prepares the module to play digitized
   sounds.
---------------------------------------------------------------------*/

int CMS_Init(int soundcard)
{
    if (CMS_Installed)
    {
        CMS_Shutdown();
    }

    CMS_Reset();
    CMS_SetRegister(0x220, 0x18, 0x82);
    CMS_SetRegister(0x220, 0x19, 0x82);

    CMS_SoundPlaying = 0;

    CMS_CallBack = NULL;

    CMS_BufferStart = NULL;

    CMS_Installed = 1;

    return (CMS_Ok);
}

/*---------------------------------------------------------------------
   Function: CMS_Shutdown

   Ends transfer of sound data to the Sound Source.
---------------------------------------------------------------------*/

void CMS_Shutdown(void)
{
    CMS_StopPlayback();

    CMS_SoundPlaying = 0;

    CMS_BufferStart = NULL;

    CMS_CallBack = NULL;

    CMS_Installed = 0;
}
