//
// Copyright (C) 1993-1996 Id Software, Inc.
// Copyright (C) 2016-2017 Alexey Khokholov (Nuke.YKT)
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// DESCRIPTION:
//	Created by a sound utility.
//	Kept as a sample, DOOM2 sounds.
//

#include "doomtype.h"
#include "sounds.h"
#include "options.h"

//
// Information about all the music
//

musicinfo_t S_music[] =
    {
        {0},
        {"E1M1", 0},
        {"E1M2", 0},
        {"E1M3", 0},
        {"E1M4", 0},
        {"E1M5", 0},
        {"E1M6", 0},
        {"E1M7", 0},
        {"E1M8", 0},
        {"E1M9", 0},
        {"E2M1", 0},
        {"E2M2", 0},
        {"E2M3", 0},
        {"E2M4", 0},
        {"E2M5", 0},
        {"E2M6", 0},
        {"E2M7", 0},
        {"E2M8", 0},
        {"E2M9", 0},
        {"E3M1", 0},
        {"E3M2", 0},
        {"E3M3", 0},
        {"E3M4", 0},
        {"E3M5", 0},
        {"E3M6", 0},
        {"E3M7", 0},
        {"E3M8", 0},
        {"E3M9", 0},
        {"INTER", 0},
        {"INTRO", 0},
        {"BUNNY", 0},
        {"VICTOR", 0},
        {"INTROA", 0},
        {"RUNNIN", 0},
        {"STALKS", 0},
        {"COUNTD", 0},
        {"BETWEE", 0},
        {"DOOM", 0},
        {"THE_DA", 0},
        {"SHAWN", 0},
        {"DDTBLU", 0},
        {"IN_CIT", 0},
        {"DEAD", 0},
        {"STLKS2", 0},
        {"THEDA2", 0},
        {"DOOM2", 0},
        {"DDTBL2", 0},
        {"RUNNI2", 0},
        {"DEAD2", 0},
        {"STLKS3", 0},
        {"ROMERO", 0},
        {"SHAWN2", 0},
        {"MESSAG", 0},
        {"COUNT2", 0},
        {"DDTBL3", 0},
        {"AMPIE", 0},
        {"THEDA3", 0},
        {"ADRIAN", 0},
        {"MESSG2", 0},
        {"ROMER2", 0},
        {"TENSE", 0},
        {"SHAWN3", 0},
        {"OPENIN", 0},
        {"EVIL", 0},
        {"ULTIMA", 0},
        {"READ_M", 0},
        {"DM2TTL", 0},
        {"DM2INT", 0}};

//
// Information about all the sfx
//

sfxinfo_t S_sfx[] =
    {
        // S_sfx[0] needs to be a dummy for odd reasons.
        {"NONE",   0,   0},
        {"PISTOL", 64,  0},
        {"SHOTGN", 64,  0},
        {"SGCOCK", 64,  0},
        {"DSHTGN", 64,  0},
        {"DBOPN",  64,  0},
        {"DBCLS",  64,  0},
        {"DBLOAD", 64,  0},
        {"PLASMA", 64,  0},
        {"BFG",    64,  0},
        {"SAWUP",  64,  0},
        {"SAWIDL", 118, 0},
        {"SAWFUL", 64,  0},
        {"SAWHIT", 64,  0},
        {"RLAUNC", 64,  0},
        {"RXPLOD", 70,  0},
        {"FIRSHT", 70,  0},
        {"FIRXPL", 70,  0},
        {"PSTART", 100, 0},
        {"PSTOP",  100, 0},
        {"DOROPN", 100, 0},
        {"DORCLS", 100, 0},
        {"STNMOV", 119, 0},
        {"SWTCHN", 78,  0},
        {"SWTCHX", 78,  0},
        {"PLPAIN", 96,  0},
        {"DMPAIN", 96,  0},
        {"POPAIN", 96,  0},
        {"VIPAIN", 96,  0},
        {"MNPAIN", 96,  0},
        {"PEPAIN", 96,  0},
        {"SLOP",   78,  0},
        {"ITEMUP", 78,  0},
        {"WPNUP",  78,  0},
        {"OOF",    96,  0},
        {"TELEPT", 32,  0},
        {"POSIT1", 98,  0},
        {"POSIT2", 98,  0},
        {"POSIT3", 98,  0},
        {"BGSIT1", 98,  0},
        {"BGSIT2", 98,  0},
        {"SGTSIT", 98,  0},
        {"CACSIT", 98,  0},
        {"BRSSIT", 94,  0},
        {"CYBSIT", 92,  0},
        {"SPISIT", 90,  0},
        {"BSPSIT", 90,  0},
        {"KNTSIT", 90,  0},
        {"VILSIT", 90,  0},
        {"MANSIT", 90,  0},
        {"PESIT",  90,  0},
        {"SKLATK", 70,  0},
        {"SGTATK", 70,  0},
        {"SKEPCH", 70,  0},
        {"VILATK", 70,  0},
        {"CLAW",   70,  0},
        {"SKESWG", 70,  0},
        {"PLDETH", 32,  0},
        {"PDIEHI", 32,  0},
        {"PODTH1", 70,  0},
        {"PODTH2", 70,  0},
        {"PODTH3", 70,  0},
        {"BGDTH1", 70,  0},
        {"BGDTH2", 70,  0},
        {"SGTDTH", 70,  0},
        {"CACDTH", 70,  0},
        {"BRSDTH", 32,  0},
        {"CYBDTH", 32,  0},
        {"SPIDTH", 32,  0},
        {"BSPDTH", 32,  0},
        {"VILDTH", 32,  0},
        {"KNTDTH", 32,  0},
        {"PEDTH",  32,  0},
        {"SKEDTH", 32,  0},
        {"POSACT", 120, 0},
        {"BGACT",  120, 0},
        {"DMACT",  120, 0},
        {"BSPACT", 100, 0},
        {"BSPWLK", 100, 0},
        {"VILACT", 100, 0},
        {"NOWAY",  78,  0},
        {"BAREXP", 60,  0},
        {"PUNCH",  64,  0},
        {"HOOF",   70,  0},
        {"METAL",  70,  0},
        {"CHGUN",  64,  0},
        {"BDOPN",  100, 0},
        {"BDCLS",  100, 0},
        {"FLAME",  32,  0},
        {"FLAMST", 32,  0},
        {"GETPOW", 60,  0},
        {"BOSPIT", 70,  0},
        {"BOSCUB", 70,  0},
        {"BOSSIT", 70,  0},
        {"BOSPN",  70,  0},
        {"BOSDTH", 70,  0},
        {"MANATK", 70,  0},
        {"MANDTH", 70,  0},
        {"SSSIT",  70,  0},
        {"SSDTH",  70,  0},
        {"KEENPN", 70,  0},
        {"KEENDT", 70,  0},
        {"SKEACT", 70,  0},
        {"SKESIT", 70,  0},
        {"SKEATK", 70,  0}};
